name: evaleng
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pydantic>=2
  - pyyaml
  - stanza
  - spacy
  - rapidfuzz
  - jellyfish
  - pytest
  - pip
  - pip:
      - wn
      - text2num==3.*